export const INITIALIZEPOKEMONS = 'INITIALIZEPOKEMONS';
export const INITIALIZEREGIONS = 'INITIALIZEREGIONS';
export const FETCHPOKEMONS = 'FETCHPOKEMONS';
export const ADDTEAM = 'ADDTEAM';
export const REMOVETEAM = 'REMOVETEAM';
export const UPDATETEAM = 'UPDATETEAM';
export const ADDPOKEMON = 'ADDPOKEMON';
export const REMOVEPOKEMON = 'REMOVEPOKEMON';
